config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :graders

  resources :courses do
    resources :sections
  end
  resources :pages do 
    member { patch :toggle_reviewed }
  end

  post 'courses/reload_courses'
  
  # Using devise for the users model
  devise_for :users


  # Routing to grader application form
  get '/graders', to: 'graders#index'
  
  root 'pages#home'
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord

    has_one :grader

    VALID_EMAIL_REGEX = /\w+\.\d+@osu\.edu/
    validates_presence_of :student_firstname, :student_lastname

    validates :student_email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

    
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: %i[ show edit update destroy ]

  # GET /recommendations or /recommendations.json
  def index
    @recommendations = Recommendation.all
  end

  # GET /recommendations/1 or /recommendations/1.json
  def show
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
    @courses = Course.pluck(:catalognumber)
    if params[:course_id]
      @section = Course.find(params[:course_id]).sections.find(params[:id])
    else
      @section = []
    end
  end

  # GET /recommendations/1/edit
  def edit
    @courses = Course.pluck(:catalognumber)
    if params[:course_id]
      @section = Course.find(params[:course_id]).sections.find(params[:id])
    else
      @section = []
    end
  end

  # POST /recommendations or /recommendations.json
  def create
    @recommendation = Recommendation.new(recommendation_params)

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to recommendation_url(@recommendation), notice: "Recommendation was successfully created." }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1 or /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to recommendation_url(@recommendation), notice: "Recommendation was successfully updated." }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1 or /recommendations/1.json
  def destroy
    @recommendation.destroy

    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: "Recommendation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recommendation_params
      params.require(:recommendation).permit(:student_firstname, :student_lastname, :student_email, :course_index, :course_section, :reasons)
    end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<%= form_with(model: recommendation) do |form| %>
  <% if recommendation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
        <% recommendation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :student_firstname, style: "display: block" %>
    <%= form.text_field :student_firstname %>
  </div>

  <div>
    <%= form.label :student_lastname, style: "display: block" %>
    <%= form.text_field :student_lastname %>
  </div>

  <div>
    <%= form.label :student_email, style: "display: block" %>
    <%= form.email_field :student_email %>
  </div>

  <div>
    <%= form.label :course_index, style: "display: block" %>
    <%= form.select :course_index, @courses %> 
  </div>

  <div>
    <%= form.label :course_section, style: "display: block" %>
    <%= form.select :course_section, @section %>
  </div>

  <div>
    <%= form.label :reasons, style: "display: block" %>
    <%= form.text_area :reasons %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recommendations/_recommendation.html.erb
<div id="<%= dom_id recommendation %>">
  <p>
    <strong>Student firstname:</strong>
    <%= recommendation.student_firstname %>
  </p>

  <p>
    <strong>Student lastname:</strong>
    <%= recommendation.student_lastname %>
  </p>

  <p>
    <strong>Student email:</strong>
    <%= recommendation.student_email %>
  </p>

  <p>
    <strong>Course index:</strong>
    <%= recommendation.course_index %>
  </p>

  <p>
    <strong>Course section:</strong>
    <%= recommendation.course_section %>
  </p>

  <p>
    <strong>Reasons:</strong>
    <%= recommendation.reasons %>
  </p>

</div>

app/views/recommendations/edit.html.erb
<% if current_user %>
  <h1>Editing recommendation</h1>

  <%= render "form", recommendation: @recommendation %>

  <br>

  <div>
    <%= link_to "Show this recommendation", @recommendation %> |
    <%= link_to "Back to recommendations", recommendations_path %>
  </div>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/recommendations/index.html.erb
<%= stylesheet_link_tag "recommendations" %>
<% if current_user %>
  <h1>Recommendations</h1>

  <div class="recommendations">
    <% @recommendations.each do |recommendation| %>
      <%= render recommendation %>
      <p>
        <%= link_to "Show this recommendation", recommendation %>
      </p>
    <% end %>
  </div>

  <%= link_to "New recommendation", new_recommendation_path %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/recommendations/new.html.erb
<% if current_user %>
  <h1>New recommendation</h1>

  <%= render "form", recommendation: @recommendation %>

  <br>

  <div>
    <%= link_to "Back to recommendations", recommendations_path %>
  </div>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/recommendations/show.html.erb
<% if current_user %>
  <%= render @recommendation %>

  <div>
    <%= link_to "Edit this recommendation", edit_recommendation_path(@recommendation) %> |
    <%= link_to "Back to recommendations", recommendations_path %>

    <%= button_to "Destroy this recommendation", @recommendation, method: :delete %>
  </div>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>