config/routes.rb
Rails.application.routes.draw do
  resources :recommendations
  resources :graders

  resources :courses do
    resources :sections
  end
  resources :pages do 
    member { patch :toggle_reviewed }
  end

  post 'courses/reload_courses'
  
  # Using devise for the users model
  devise_for :users


  # Routing to grader application form
  get '/graders', to: 'graders#index'
  
  root 'pages#home'
end

app/models/grader.rb
class Grader < ApplicationRecord
  belongs_to :recommendation, optional: true
  belongs_to :user

  serialize :classes, Array
  
  CLASSES = @courses

  serialize :available_times, Array

  AVAILABLE_TIMES = %w[8:00AM_-_9:00AM 9:00AM_-_10:00AM 10:00AM_-_11:00AM 11:00AM_-_12:00PM 12:00PM_-_1:00PM 1:00PM_-_2:00PM 2:00PM_-_3:00PM 3:00PM_-_4:00PM 4:00PM_-_5:00PM 5:00PM_-_6:00PM 6:00PM_-_7:00PM 7:00PM_-_8:00PM]

  VALID_EMAIL_REGEX = /\w+\.\d+@osu\.edu/

  validates_presence_of :first_name, :last_name

  # Custom email validation
  validates :email, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  # Courses must be selected
  validates_presence_of :classes
  
  # Times must be selected
  validates_presence_of :available_times
end

app/controllers/graders_controller.rb
class GradersController < ApplicationController
  before_action :set_grader, only: %i[ show edit update destroy ]

  JSON_REQUEST = 'https://content.osu.edu/v2/classes/search?q=cse&campus=col&p=1&term=1222'

  # GET /graders or /graders.json
  def index
    @graders = Grader.all
  end

  # GET /graders/1 or /graders/1.json
  def show
  end

  # GET /graders/new
  def new
    @grader = Grader.new
    @courses = Course.all
  end

  # GET /graders/1/edit
  def edit
    @courses = Course.all
  end

  # POST /graders or /graders.json
  def create
    # @user = User.find(params[:current_user.id)
    @user = User.find(current_user.id)
    # @user = User.find_by(email: 'Lifo')
    # @grader = @user.grader.create(grader_params)
    @grader = @user.create_grader(grader_params)
    # current_user.grader = Grader.new({})
    # @grader = Grader.new(grader_params)
    @courses = Course.all

    respond_to do |format|
      if @grader.save
        format.html { redirect_to grader_url(@grader), notice: "Grader was successfully created." }
        format.json { render :show, status: :created, location: @grader }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @grader.errors, status: :unprocessable_entity }
      end
    end
  end

  # def create
  #   @recommendation = Recommendation.find(params[:recommendation_id])
  #   # @grader = @recommendation.grader.create(grader_params)
  #   @grader = Grader.new(grader_params)

  #   respond_to do |format|
  #     if @grader.save
  #       format.html { redirect_to grader_url(@grader), notice: "Grader was successfully created." }
  #       format.json { render :show, status: :created, location: @grader }
  #     else
  #       format.html { render :new, status: :unprocessable_entity }
  #       format.json { render json: @grader.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /graders/1 or /graders/1.json
  def update
    # assign grader and increment section assignee count
    if params[:grader] && params[:grader].length == 1
      @grader.section_id = params[:grader][0]
      @grader.save
      @section = Section.find(@grader.section_id)
      @section.num_graders += 1
      @section.save
      grader_path(@grader)
    else
      respond_to do |format|
        if @grader.update(grader_params)
          format.html { redirect_to grader_url(@grader), notice: "Grader was successfully updated." }
          format.json { render :show, status: :ok, location: @grader }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @grader.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /graders/1 or /graders/1.json
  def destroy
    @grader.destroy

    respond_to do |format|
      format.html { redirect_to graders_url, notice: "Grader was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grader
      @grader = Grader.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def grader_params
      params.require(:grader).permit(:first_name, :last_name, :email, classes: [], available_times: [])
    end
end

app/helpers/graders_helper.rb
module GradersHelper
end

app/views/graders/_form.html.erb
<%= form_with(model: grader) do |f| %>
  <% if grader.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(grader.errors.count, "error") %> prohibited this grader from being saved:</h2>

      <ul>
        <% grader.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %>
  </div>
  
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

  <div class="field checkbox">
    <%= f.label "Interested Courses" %>
    <br /><% @courses.each do |key| %>
      <% if !key.sections.nil? %>
        <%= f.check_box :classes, { multiple: true}, key.id, nil %>
        <%= f.label key.subject %>
        <%= f.label key.catalognumber %><br />
      <% end %>
    <% end %>
  </div>

  <div class="field checkbox">
    <%= f.label "Available Time" %>
    <br /><% Grader::AVAILABLE_TIMES.each do |key| %>
      <%= f.check_box :available_times, { multiple: true}, key, nil %>
      <%= f.label key %><br />
    <% end %>
  </div>

  <div>
    <br /><%= f.submit %>
  </div>
<% end %>

app/views/graders/_form2.html.erb
<%# Form for assigning graders to sections %>
<%= form_with model: @grader do |f| %>
    <%# Combine contiguous grader windows %>
    <% grader_windows = Array.new %>
    <% @grader.available_times.each do |window| %>
        <% if grader_windows.length > 0 && (grader_windows.last.split('_')[2] === window.split('_')[0]) %>
            <% prev_window = grader_windows.pop %>
            <% new_window = prev_window.split('_')[0] + "_-_" + window.split('_')[2] %>
            <% grader_windows.push(new_window) %>
        <% elsif !grader_windows.include?(window) %>
            <% grader_windows.push(window) %>
        <% end %>
    <% end %>
    <div class="field radio">
    <% @grader.classes.each do |course_id| %>
        <% course = Course.find(course_id) %>
        <% if course.sections.length > 0 %>
        <%= course.subject + " " + course.catalognumber + ":" %><br />
        <% course.sections.each do |section| %>
            <% if section.num_graders < section.graders_needed %>
                <% grader_windows.each do |window| %>
                    <%# Grader's window is in both morning and afternoon %>
                    <% if @grader.available_times.first.include?("AM") && @grader.available_times.last.include?("PM") %>
                        <% if section.end_time.split(' ')[0] < window.split('_')[0] || section.start_time.split(' ')[0] > window.split('_')[2] %>
                            <% next %>
                        <% end %> 
                    <%# Grader's window is only in the afternoon %>
                    <% elsif @grader.available_times.first.include?("PM") && @grader.available_times.last.include?("PM") %>
                        <%# Skip all AM sections %>
                        <% if section.start_time.include?("am") || section.end_time.include?("am") %>
                            <% next %>
                        <% end %> 
                    <%# Grader's window is only in the morning %>
                    <% elsif @grader.available_times.first.include?("AM") && @grader.available_times.last.include?("AM") %>
                        <%# Skip all PM sections %>
                        <% if section.start_time.include?("pm") || section.end_time.include?("pm") %>
                            <% next %>
                        <% end %>
                    <% end %>
                    <% if window.split('_')[0] <= section.start_time.split(' ')[0] && section.end_time.split(' ')[0] <= window.split('_')[2] %>
                        <%= f.radio_button @grader.section_id, section.id %>
                        <%= f.label section.number + " | " + section.mode + " | " + section.start_time + "-" + section.end_time %>
                        <br />
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
        <br />
        <% end %>
    <% end %>
    </div>
    <div>
    <%= f.submit "Assign Grader" %>
    </div>
<% end %>

app/views/graders/_grader.html.erb
<div id="<%= dom_id grader %>">
  <tr>
    <td><%= grader.first_name %></td>
    <td><%= grader.last_name %></td>
    <td><%= grader.email %></td>
    <td>
      <% grader.classes.each do |course_id| %>
        <% course = Course.find(course_id) %>
        <%= course.subject + " " + course.catalognumber %> |
      <% end %>
    </td>
    <td>
      <% grader.available_times.each do |time| %>
        <%= time %> |
      <% end %>
    </td>
</div>

app/views/graders/edit.html.erb
<% if current_user %>
  <h1>Editing grader</h1>

  <%= render "form", grader: @grader %>

  <br>

  <div>
    <%= link_to "Show this grader", @grader %> |
    <%= link_to "Back to graders", graders_path %>
  </div>
<% else %>
  <p> You are not signed in. </p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/graders/index.html.erb
<h1>Graders</h1>
<% if current_user %>
  <table id="graders">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Interested Courses</th>
      <th>Available Time(s)</th>
      <th>View Grader App</th>
    </tr>
    <% @graders.each do |grader| %>
      <%= render grader %>
      <% if current_user.email.casecmp(grader.email).zero? || current_user.admin? %>
        <td>
          <%= link_to "Show this grader", grader %>
        </td>
      <% end %>
      </tr>
    <% end %>
  </table>
  <% if current_user.student? %>
    <%= link_to "New grader", new_grader_path %>
  <% end %>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/graders/new.html.erb
<% if current_user %>
<h1>Student Grader Application</h1>

<%= render "form", grader: @grader %>

<button class="linking">
  <%= link_to "Back to graders", graders_path %>
</button>
<% else %>
  <p> You are not signed in. </p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

app/views/graders/show.html.erb
<% if current_user %>
  <h1>Filled Out Grader Application</h1>
  <table>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Interested Courses</th>
      <th>Available Time(s)</th>
    </tr>
    <%= render @grader %>
    </tr>
  </table>

  <br />
  <% if current_user.admin? && @grader.section_id.nil? %>
    <h3>Assign Grader to a Section</h3>
    <%= render "form2", grader: @grader %>
  <% elsif current_user.admin? && !@grader.section_id.nil? %>
    <% section = Section.find(@grader.section_id) %>
    <p>Grader is currently assigned to <% section.course.subject + " " + section.course.catalognumber %> section <%= section.number %>.</p>
  <% end %>

  <div class="lined-up linking">
    <% if current_user.email.casecmp(@grader.email).zero? %>
      <%= link_to "Edit grader application", edit_grader_path(@grader) %> |
    <% end %>
    <%= link_to "Back to graders", graders_path %>
    <% if current_user.admin? && current_user.present? %>
      | <%= button_to "Destroy this grader", @grader, method: :delete, :style => "margin-left: 0.2rem;" %>
    <% end %>
  </div>
<% else %>
  <p>You are not signed in.</p>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>